---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jjit-cache
  labels:
    type: local
spec:
   capacity:
    storage: 1Gi
   accessModes:
    - ReadWriteOnce
   hostPath:
     path: /jjit_cache/
